new methods
interpretml/interpret pull request #469
Opened 2023-08-11 19:14 UTC by brandongreenwell-8451

This PR addresses https://github.com/interpretml/interpret/issues/460 by adding two new methods to a fitted EBM object: 
* `reweight_terms()` - which allows callers to reweight the individual term contributions of the fit;
* `remove_terms()` - which allows callers to remove specific terms (and their associated components).

2023-08-11 19:19 UTC, brandongreenwell-8451 commented
@paulbkoch it was just easier to start afresh and create a new PR (I'm also not the most Git/GH savvy of statisticians...). This version places the `remove_nil_terms` argument over to the `reweight_terms()` method and internally calls `remove_terms()` when set to `True`.

**Note:** This works great on my end, but not sure if the return statement on line 2267 is the most Pythonic way to handle the nested call to `remove_terms()`.

2023-08-11 19:26 UTC, brandongreenwell-8451 commented
> Hi @brandongreenwell-8451 -- We definitely need some kind of remove_terms function that only operates on the terms given to it by the caller. The eventual ISLE function does not need this, but EBMs do as a general ability, so I figure it's best to have it as a primitive that is called by reweight.
>
>Another small nuance: I think the reweigh_terms function should only remove terms that have 0 in the given weight parameter, not check if any of the resulting term scores are all zero. If some of the terms had all zeros in their scores before the call to reweigh_terms, then the caller would need to do a lot of checks to know which terms to expect will be dropped, and that behavior would be surprising, I think. Safer to force the caller to be more explicit in this case and call remove_terms themselves in the special case that there are terms with all zeros and they want them removed. It's pretty unlikely we'd see a term with all zeros naturally anyways, except if the user previously edited the EBM (in which case whatever they called to do that could also have a remove_nil_terms parameter), or in the case of a feature with only 1 value. In the latter case LASSO would give it a weight of 0 anyways I think, so those terms would be dropped anyways in an ISLE implementation.

I think we're aligned on your first comment in this PR, right? Copy on the second and will send an update shortly!

2023-08-11 19:38 UTC, brandongreenwell-8451 commented
And the DCO check passed...🥳

2023-08-11 19:57 UTC, paulbkoch requested changes

2023-08-11 19:57 UTC, paulbkoch commented on python/interpret-core/interpret/glassbox/_ebm/_ebm.py
> +    def remove_terms(self, term_list):
I'd like to call this "terms" instead of "term_list" and accept any enumerable object (could be a numpy array for instance)

2023-08-11 19:57 UTC, paulbkoch commented on python/interpret-core/interpret/glassbox/_ebm/_ebm.py
> +        # Copy any fields we'll overwrite in case someone has a shallow copy of self
These copies are not required in this case since we later use a list comprehension which will create a new list.

2023-08-11 19:57 UTC, paulbkoch commented on python/interpret-core/interpret/glassbox/_ebm/_ebm.py
> +            remove_nil_terms: Logical indicating whether or not to automatically
Boolean instead of Logical in python  ;)

2023-08-11 19:57 UTC, paulbkoch commented on python/interpret-core/interpret/glassbox/_ebm/_ebm.py
> +
We're only modifying term_scores, bagged_scores, and standard_deviations, so we don't need copies of the others

2023-08-11 19:57 UTC, paulbkoch commented on python/interpret-core/interpret/glassbox/_ebm/_ebm.py
> +            # FIXME: Does it make sense to omit the missing and unknown bins (first
For reweighing we should do it for all bins, so we don't need the slice of "1,-1"

2023-08-11 19:57 UTC, paulbkoch commented on python/interpret-core/interpret/glassbox/_ebm/_ebm.py
> +            term_list = np.where(self.term_importances() == 0)[0].tolist()
Instead of using term_importances, use weights parameter (and accept any enumerable)

2023-08-11 20:03 UTC, paulbkoch commented
Thanks @brandongreenwell-8451 -- Looks pretty good!  I noted a few small things to change.  Also, please pip install the black formatter, and run "black ." on the command line to pass the final black formatting check in the build.

2023-08-11 20:35 UTC, paulbkoch commented
Also, could you add a unit test for each of these in:

https://github.com/interpretml/interpret/blob/develop/python/interpret-core/tests/glassbox/ebm/test_ebm.py

2023-08-14 09:57 UTC, paulbkoch commented
I had an additional thought over the weekend regarding naming.  I think for someone new to InterpretML who has not read the documentation, reweigh_terms might be misinterpreted as weighing/measuring something within the EBM rather than something that applies a multiplication factor.  We also use "weight" inside the EBM for the bin_weights_ attribute which might lead someone to guess they are related.  The alternative name I came up with was:

def scale_terms(self, factors, remove_nil_terms=False):

2023-08-14 16:25 UTC, brandongreenwell-8451 commented
> I had an additional thought over the weekend regarding naming. I think for someone new to InterpretML who has not read the documentation, reweigh_terms might be misinterpreted as weighing/measuring something within the EBM rather than something that applies a multiplication factor. We also use "weight" inside the EBM for the bin_weights_ attribute which might lead someone to guess they are related. The alternative name I came up with was:
> 
> def scale_terms(self, factors, remove_nil_terms=False):

That seems reasonable to me! I'll make that change later this week when I work on your other suggestions.

2023-08-14 20:07 UTC, brandongreenwell-8451 commented
@paulbkoch I think this addresses all your concerns/suggestions if you want to take another look.

2023-08-15 04:13 UTC, merged

2023-08-15 04:13 UTC, paulbkoch commented
Looks great!  Thanks for contributing this @brandongreenwell-8451

2023-08-15 10:09 UTC, bgreenwell commented
Awesome @paulbkoch, thanks for the support I’m getting this through!